name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Run pre-commit
        run: pre-commit run --all-files

  tests:
    name: "Python ${{ matrix.python-version }}"
    needs: linter
    runs-on: ubuntu-latest

    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m coverage run -m pytest
          python -m coverage report
